UI and Backend for private-events
happiguru/private-event pull request #2
Opened 2020-10-22 20:47 UTC by Miguelus373

## What this PR does:
- Adds all the MVC for this page
- Adds all the associations between the models
- Adds all the validations for the models
- Adds user interface to the page

2020-10-22 22:51 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [x] Let's include a screenshot in the readme.MD file.
- [x] The Private Event title in the readme.MD file should start with a capital letter 
- [x] Let's remove all JSON formats.
- [x] View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
- [x] Let's use only Rspec and capybara for testing ,I can see a `test` DIR which is used when using Minitest, remove it .
* [ ] authentication has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] event managment features has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
### [OPTIONAL]
### Routes
* [x] routes only for used actions, i.e. `resources :events, only: [:new, :create, :show, :index]`
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-10-22 22:51 UTC, kobiyoyo commented on app/controllers/events_controller.rb
> +  end
##### EventsController
###### `index` action

* [ ] lists past events ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-10-22 22:51 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +  def show; end
##### UsersController

###### `show` action

* [ ] lists events created by user([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previoulsy attendented by user **using event model scope** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-10-23 01:49 UTC, happiguru commented on app/controllers/users_controller.rb
> +  def show; end
Resolved

2020-10-23 01:49 UTC, happiguru commented on app/controllers/events_controller.rb
> +  end
Resolved

2020-10-23 18:35 UTC, christianotieno approved these changes
### Project Approved 🍾 

Hello @Miguelus373 & @happiguru 👋 
Congratulations on the hard work with the changes. keep it up 👏 
All the required changes have been fulfilled in this project. I will go ahead and mark it as complete 👍 
I wish you all the best in the next tasks 🥇 

### Happy coding 💻 

#### Christian Otieno (TSE)

2020-10-23 19:13 UTC, merged